on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: install cloudflared
      run: |
        sudo mkdir -p --mode=0755 /usr/share/keyrings
        curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
        echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared noble main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
        sudo apt-get update && sudo apt-get install cloudflared
    - name: install ssh keys, change ssh config
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo done1
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo done2
        touch ~/.ssh/config
        echo done3
        echo "Host ${{ secrets.SSH_HOSTNAME }}" >> ~/.ssh/config
        echo done4
        echo "ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h" >> ~/.ssh/config
        echo done5
        ssh-keyscan -H ${{ secrets.SSH_HOSTNAME }} > ~/.ssh/known_hosts
        echo done6
    - name: connect, pull, start server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }}
        cd King-of-the-Cards 
        git checkout master 
        git pull 
        pkill screen
        screen -d -m -S SERVER dotnet run --project ~/King-of-the-Cards/KC.Backend.API/KC.Backend.API.csproj --launch-profile 'http-public'
        exit
    - name: cleanup
      run: rm -rf ~/.ssh
