on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  run_push:
    name: Push on release -> deploy
    runs-on: ubuntu-latest

    steps:
    - name: Install WireGuard
      run: sudo apt update && sudo apt install wireguard -y
      
    - name: Create tunnel config
      run: |
        echo "[Interface]
          PrivateKey = ${{ secrets.WG_PRIVATE_KEY }}
          Address = 172.16.0.2/32

          [Peer]
          PublicKey = ${{ secrets.WG_PEER_PUBLIC_KEY }}
          AllowedIPs = 172.16.0.1/32
          Endpoint = ${{ secrets.WG_HOST }}:51820
          PersistentKeepalive = 25" > wg0.conf
          
    - name: Establish Tunnel
      run: |
        sudo wg-quick up ./wg0.conf
        ping -c 3 172.16.0.1  # Verify connection
        
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        {
          echo "Host 172.16.0.1"
          echo "  StrictHostKeyChecking=no"
          echo "  UserKnownHostsFile=/dev/null"
        } >> ~/.ssh/config
        
    - name: Connect and Pull Code
      run: |
        ssh_retry() {
          for i in {1..3}; do
            {
              echo "set -e"
              echo "cd ~/King-of-the-Cards"
              echo "git checkout release"
              echo "git pull"
              echo "sudo systemctl restart kc-backend.service"
            } | ssh -o ConnectTimeout=10 ${{ secrets.SSH_USER }}@172.16.0.1 && break || sleep 5
            echo "SSH attempt $i failed, retrying..." >&2
          done
        }
        ssh_retry
        
    - name: Cleanup
      if: always()
      run: rm -rf ~/.ssh && rm ./wg0.conf
